CREATE TABLE public.supplier (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL,
  supplier_code VARCHAR(50) UNIQUE,
  type public.entity_type_enum,
  company_name VARCHAR(255),
  ice VARCHAR(50),
  rc VARCHAR(50),
  tax_id VARCHAR(50),
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  email VARCHAR(255),
  phone VARCHAR(50),
  mobile VARCHAR(50),
  website VARCHAR(255),
  address TEXT,
  city VARCHAR(100),
  country VARCHAR(100),
  category VARCHAR(100),
  notes TEXT,
  payment_terms VARCHAR(50),
  bank_name VARCHAR(100),
  bank_account VARCHAR(100),
  iban VARCHAR(100),
  swift VARCHAR(50),
  currency VARCHAR(10),
  status public.status_enum DEFAULT 'active',
  created_by UUID,
  updated_by UUID,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_supplier_org ON public.supplier(organization_id);
